export { default as DashboardRoute } from './dashboard.jsx'
export { default as RecordActionRoute } from './record-action.jsx'
export { default as ResourceActionRoute } from './resource-action.jsx'
export { default as BulkActionRoute } from './bulk-action.jsx'
export { default as PageRoute } from './page.jsx'
export { default as ResourceRoute } from './resource.jsx'
