export { default as DashboardRoute } from './dashboard'
export { default as RecordActionRoute } from './record-action'
export { default as ResourceActionRoute } from './resource-action'
export { default as BulkActionRoute } from './bulk-action'
export { default as PageRoute } from './page'
export { default as ResourceRoute } from './resource'
