export * from './action-json.interface'
export * from './page-json.interface'
export * from './property-json.interface'
export * from './record-json.interface'
export * from './resource-json.interface'
