import React from 'react'
import PropTypes from 'prop-types'
import styled, { createGlobalStyle } from 'styled-components'

import WrapperBox from '../ui/wrapper-box'
import StyledButton from '../ui/styled-button'
import PropertyInEdit from '../ui/property-in-edit'
import { colors, fonts, sizes } from '../../styles/variables'

const GlobalStyle = createGlobalStyle`
  html, body, #app {
    width: 100%;
    height: 100%;
    background: ${colors.bck};
    font-size: ${fonts.base};
  }

  a {
    color: ${colors.primary};
  }
`

const FlexWrapper = styled.section`
  display: flex;
  height: 100%;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background-color: ${colors.loginBck};
  background-image: url('/admin/frontend/assets/login-bg.png');
  background-repeat: no-repeat;
  background-position: bottom right;
  background-size: 100%;
`

const LoginBox = styled.section`
  display: flex;
  flex-direction: row;
  padding: 0;
  font-family: 'Roboto', sans-serif;

  & .content {
    text-align: center;
    border-bottom: 1px solid ${colors.border};
    margin: 0 -${sizes.paddingLayout} ${sizes.paddingLayout};
    padding-bottom: ${sizes.paddingLayout};
  }

  & .panel {
    padding: 64px 48px;
    width: 446px;
    height: 100%;
  }

  & .leftPanel {
    background-image: url('/admin/frontend/assets/login-left.jpg');
    background-size: cover;
    background-position: right;

    h1 {
      color: ${colors.gray};
      font-size: ${fonts.header};
    }

    p {
      font-size: ${fonts.base};
      color: ${colors.gray};
    }
  }

  & .rightPanel {
    background-color: ${colors.white};

    .logo {
      margin-bottom: 48px;
    }

    .notification.is-danger {
      background-color: ${colors.loginInfo};
      color: ${colors.gray};
      font-size: ${fonts.base};
      padding: 12px;
    }

    label {
      font-size: 12px;

    }
  }
`

const Login = (props) => {
  const { action, message } = props
  const email = { name: 'email', label: 'Email' }
  const password = { name: 'password', label: 'Password' }

  return (
    <React.Fragment>
      <GlobalStyle />
      <FlexWrapper>
        <LoginBox>
          <div className="leftPanel panel">
            <h1>Welcome!</h1>
            <p>AdminBro is a first autogenerated admin <br/>panel for Node.js apps based on React.</p>
          </div>
          <div className="rightPanel panel">
            <img src='/admin/frontend/assets/logo.svg' className="logo"/>
            {message && <div className="notification is-danger">{message}</div>}
            <form action={action} method="POST">
              <PropertyInEdit property={email} className="field">
                <input type="text" name="email" placeholder="Your Email Address" className="input" />
              </PropertyInEdit>
              <PropertyInEdit property={password} className="field">
                <input type="password" name="password" placeholder="Password" className="input" />
              </PropertyInEdit>
              <StyledButton as="button" type="submit" className="is-primary is-fullwidth">
                Start
              </StyledButton>
            </form>
          </div>
        </LoginBox>
      </FlexWrapper>
    </React.Fragment>
  )
}

Login.propTypes = {
  message: PropTypes.string,
  action: PropTypes.string.isRequired,
}

Login.defaultProps = {
  message: null,
}

export default Login
