export { default as Table } from './table'
export { default as TableHead } from './table-head'
export { default as TableBody } from './table-body'
export { default as TableCell } from './table-cell'
export { default as TableRow } from './table-row'
export { default as TableCaption } from './table-caption'
